#!/usr/bin/env python3
"""
Index a project-context snapshot for reading by section.

    python3 tools/context_index.py <snapshot-dir> [--out <dir>]

Writes two files into --out (default: the snapshot's parent):

    INDEX.md          every file under the snapshot, in path order. For each
                      markdown file: bytes, short sha256, and every heading
                      with its line number, so a reader can `view` a section
                      by line range instead of reading the document whole.
    MANIFEST.sha256   `<sha256>  <path>` for every file, paths relative to
                      --out, in `sha256sum -c` format. Verifies a restored
                      copy byte for byte.

The Drive connector reads a file whole; the sandbox reads by line range. This
index is what makes the second cheaper than the first. It carries no content —
headings and numbers only — so it reveals structure, not text, and is safe to
leave in cleartext beside the ciphertext if that is ever useful.

Standard library only: the Mirror workflow runs it on a bare runner.
"""

from __future__ import annotations

import argparse
import hashlib
import re
import sys
from pathlib import Path

HEADING = re.compile(r"^(#{1,4})\s+(.*\S)\s*$")
FENCE = re.compile(r"^\s*(```|~~~)")


def sha256_of(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 16), b""):
            h.update(chunk)
    return h.hexdigest()


def headings(path: Path) -> list[tuple[int, int, str]]:
    """(line number, level, title) for every heading outside a code fence.
    Fences matter: a shell comment inside a ``` block is not a heading."""
    out: list[tuple[int, int, str]] = []
    in_fence = False
    with path.open(encoding="utf-8", errors="replace") as fh:
        for n, line in enumerate(fh, 1):
            if FENCE.match(line):
                in_fence = not in_fence
                continue
            if in_fence:
                continue
            m = HEADING.match(line)
            if m:
                out.append((n, len(m.group(1)), m.group(2)))
    return out


def build(snapshot: Path, out: Path) -> tuple[int, int]:
    files = sorted(p for p in snapshot.rglob("*") if p.is_file())
    if not (snapshot / "README.md").is_file():
        sys.exit(f"refusing: {snapshot} has no README.md, so it is not a complete snapshot")

    index: list[str] = [
        f"# INDEX — {snapshot.name}",
        "",
        "Generated by `tools/context_index.py`. Headings with line numbers, so a",
        "section can be read by line range. Sizes in bytes; hashes are sha256,",
        "first 16 hex digits; the full digests are in `MANIFEST.sha256`.",
        "",
        "Read `SESSION-HANDOVER.md` first, then `LESSONS.md`.",
        "",
    ]
    manifest: list[str] = []
    total = 0
    for p in files:
        rel = p.relative_to(snapshot).as_posix()
        size = p.stat().st_size
        total += size
        digest = sha256_of(p)
        manifest.append(f"{digest}  {snapshot.name}/{rel}")
        index.append(f"## `{rel}` — {size:,} bytes, {digest[:16]}")
        if p.suffix.lower() == ".md":
            hs = headings(p)
            if hs:
                for n, level, title in hs:
                    index.append(f"- L{n} {'#' * level} {title}")
            else:
                index.append("- (no headings)")
        index.append("")

    index[5:5] = ["", f"{len(files)} files, {total:,} bytes."]
    out.mkdir(parents=True, exist_ok=True)
    (out / "INDEX.md").write_text("\n".join(index).rstrip() + "\n", encoding="utf-8")
    (out / "MANIFEST.sha256").write_text("\n".join(manifest) + "\n", encoding="utf-8")
    return len(files), total


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("snapshot", type=Path, help="the dated snapshot folder")
    ap.add_argument("--out", type=Path, default=None,
                    help="where INDEX.md and MANIFEST.sha256 go (default: snapshot's parent)")
    a = ap.parse_args()
    snapshot = a.snapshot.resolve()
    out = (a.out or snapshot.parent).resolve()
    if not snapshot.is_dir():
        sys.exit(f"not a directory: {snapshot}")
    n, total = build(snapshot, out)
    print(f"indexed {snapshot.name}: {n} files, {total:,} bytes -> {out / 'INDEX.md'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
